spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

  cache:
    type: simple

  jpa:
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true

logging:
  level:
    com.zeyvo: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

zeyvo:
  jwt:
    secret: dev-secret-minimum-32-characters-long
  rate-limit:
    enabled: false
